soft-keyboard-toggle-behavior = enable

terminal-transcript-rows = 10000

extra-keys = [['ESC', '~', '/', 'HOME', 'UP', 'END', 'PGUP'], \
              ['TAB', 'CTRL', 'ALT', 'LEFT', 'DOWN', 'RIGHT', 'PGDN']]
